Repository thisiskartikgupta/Atlantisian-And-The-Mermaid, pull requests merged in 2020-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: hacktoberfest-accepted

#3 Add files via upload
  AWESOME EARTH.png
Labels: documentation, enhancement, hacktoberfest-accepted

#4 Create new_file.txt
  new_file.txt
Labels: enhancement, hacktoberfest-accepted

#5 Add files via upload
  amazon.html
Labels: documentation, enhancement, hacktoberfest-accepted

#6 Add files via upload
  colour.py
  python.py
Labels: enhancement, hacktoberfest-accepted

#7 Add files via upload
  file.py
Labels: enhancement, hacktoberfest-accepted
